name: Run test & deploy bowling application.

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t bowling .

      - name: Start bowling container
        run: docker run -d -p 3000:80 bowling

      - name: Wait for bowling app to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests in Chrome headless
        run: npm run test:cypress:ci
