name: Run test & deploy bowling application.

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create cypress

      - name: Build docker image
        run: docker build -t bowling .

      - name: Stop old container (if exists)
        run: docker ps -q --filter "name=bowling" | xargs -r docker stop

      - name: Start bowling container
        run: docker run -d --network cypress --name bowling -p 3000:80 bowling

      - name: Run e2e test cases
        run: |
          docker run --rm \
            --network cypress \
            -v ${{ github.workspace }}:/cypress/e2e \
            -w /e2e \
            cypress/included:13.5.0 \
            --config baseUrl=http://bowling
